# Generated by Django 4.2.6 on 2023-10-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0002_alter_sensor_hive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='token_last_refreshed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
