# Generated by Django 4.2.6 on 2023-10-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0004_sensor_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
