# Generated by Django 4.2.6 on 2023-10-19 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0005_datatransmission_sensordata_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaryhub',
            old_name='status',
            new_name='hub_status',
        ),
        migrations.RenameField(
            model_name='datatransmission',
            old_name='apiary_hub',
            new_name='apiary_uuid',
        ),
        migrations.RemoveField(
            model_name='datatransmission',
            name='tansmission_tries',
        ),
        migrations.AddField(
            model_name='datatransmission',
            name='transmission_tries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='apiaryhub',
            name='battery_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='apiaryhub',
            name='software_version',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
