# Generated by Django 4.2.6 on 2023-10-17 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0006_sensor_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='apiary_central.hive'),
        ),
    ]
