# Generated by Django 4.2.6 on 2023-10-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0007_merge_20231019_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='apiary_central.datatransmission'),
        ),
    ]
