# Generated by Django 4.2.6 on 2023-10-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0008_sensordata_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apiary',
            options={'verbose_name': 'Apiary', 'verbose_name_plural': 'Apiaries'},
        ),
        migrations.AlterField(
            model_name='hivecomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiary_central.hivecomponenttype'),
        ),
    ]
