# Generated by Django 4.2.6 on 2023-10-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0010_remove_hive_components_hivecomponent_hive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiary_central.sensortype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('hive', 'sensor_type')},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='type',
        ),
    ]
