# Generated by Django 4.2.6 on 2023-10-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0011_sensortype_alter_sensor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name': 'Sensor data', 'verbose_name_plural': 'Sensor data'},
        ),
    ]
