# Generated by Django 4.2.6 on 2023-10-27 01:13

import apiary_central.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0012_alter_sensordata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaryhub',
            name='hub_status',
        ),
        migrations.RemoveField(
            model_name='apiaryhub',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='authentication_token',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='token_last_refreshed',
        ),
        migrations.AddField(
            model_name='apiaryhub',
            name='api_key',
            field=models.CharField(default=apiary_central.models.generate_api_key, max_length=255, unique=True),
        ),
    ]
