# Generated by Django 4.2.6 on 2023-10-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0013_remove_apiaryhub_hub_status_remove_apiaryhub_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatransmission',
            name='apiary_uuid',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='transmission',
        ),
        migrations.DeleteModel(
            name='ApiaryHub',
        ),
        migrations.DeleteModel(
            name='DataTransmission',
        ),
    ]
