# Generated by Django 4.2.6 on 2023-10-30 08:42

import apiary_central.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryhub',
            name='api_key',
            field=models.UUIDField(default=apiary_central.models.generate_api_key, unique=True),
        ),
    ]
