# Generated by Django 4.2.6 on 2023-11-07 20:56

import apiary_central.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryhub',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, null=True, validators=[apiary_central.validators.validate_datetime]),
        ),
    ]
