# Generated by Django 4.2.7 on 2023-12-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0003_remove_sensor_ble_charateristic_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmissiontimeslot',
            old_name='slot_indicator',
            new_name='timeslot',
        ),
    ]
