# Generated by Django 4.2.6 on 2023-11-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0003_alter_apiaryhub_last_connected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaryhub',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
