# Generated by Django 4.2.6 on 2023-10-18 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0004_remove_sensordata_sensor_delete_sensor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEMP', 'Temperature'), ('WEIGHT', 'Weight'), ('HUMIDITY', 'Humidity'), ('AUDIO', 'Audio')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('authentication_token', models.CharField(max_length=255, unique=True)),
                ('token_last_refreshed', models.DateTimeField()),
                ('hive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='apiary_central.hive')),
            ],
            options={
                'unique_together': {('hive', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='apiary_central.sensor')),
            ],
        ),
    ]
