# Generated by Django 4.2.6 on 2023-10-18 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0004_apiaryhub'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransmission',
            fields=[
                ('transmission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tansmission_tries', models.IntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('apiary_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='apiary_central.apiaryhub')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='apiary_central.datatransmission'),
        ),
    ]
