# Generated by Django 4.2.6 on 2023-11-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0005_alter_sensor_last_reading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortype',
            old_name='name',
            new_name='type',
        ),
    ]
