# Generated by Django 4.2.6 on 2023-11-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0006_rename_name_sensortype_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together=set(),
        ),
    ]
