# Generated by Django 5.0 on 2023-12-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0006_apiary_timezone_alter_apiaryhub_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('hub', 'Hub')], max_length=10)),
                ('device_id', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='last_reading',
        ),
        migrations.AddField(
            model_name='apiaryhub',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
