# Generated by Django 4.2.6 on 2023-10-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0005_sensor_sensordata'),
        ('apiary_central', '0006_rename_status_apiaryhub_hub_status_and_more'),
    ]

    operations = [
    ]
