# Generated by Django 4.2.6 on 2023-11-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0007_alter_sensor_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatransmission',
            old_name='apiary',
            new_name='apiaryhub',
        ),
    ]
