# Generated by Django 5.0 on 2024-01-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0007_deviceerrorreport_remove_sensor_last_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceerrorreport',
            name='device_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceerrorreport',
            name='reported_at',
            field=models.DateTimeField(),
        ),
    ]
