# Generated by Django 4.2.6 on 2023-11-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0008_rename_apiary_datatransmission_apiaryhub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatransmission',
            old_name='apiaryhub',
            new_name='apiary_hub',
        ),
    ]
