# Generated by Django 4.2.6 on 2023-10-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0009_hivecomponenttype_alter_apiary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='components',
        ),
        migrations.AddField(
            model_name='hivecomponent',
            name='hive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='apiary_central.hive'),
            preserve_default=False,
        ),
    ]
