# Generated by Django 4.2.6 on 2023-11-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiary_central', '0010_datatransmissionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_indicator', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apiaryhub',
            name='transmission_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiary_central.transmissiontimeslot'),
        ),
    ]
